#!/usr/bin/env bash
# A Bash script that displays only the running processes containing the word "bash"
# shellcheck disable=SC2009

ps -eo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command | grep bash
