#!/usr/bin/env bash
# A Bash script that loops infinitely and prints "I am invincible!!!" on SIGTERM

# Trap the SIGTERM signal
trap 'echo "I am invincible!!!"' SIGTERM

# Infinite loop
while true; do
    echo "To infinity and beyond"
    sleep 2
done
