#!/usr/bin/env bash
# A Bash script that kills the 7-highlander process using SIGKILL

# Get all PIDs of the 7-highlander processes
PIDS=$(pgrep -f 7-highlander)

# Kill each PID individually
for PID in $PIDS; do
    kill -9 "$PID"
done
