#!/usr/bin/env bash
# A Bash script that kills the 7-highlander process using SIGKILL

# Get the PID of the 7-highlander process
PID=$(pgrep -f 7-highlander)

# Send SIGKILL (signal 9) to the process
if [ -n "$PID" ]; then
    kill -9 "$PID"
fi
