#!/usr/bin/env bash
# This script loops from 1 to 10, showing "bad luck" on 4th, "good luck" on 8th, and "Best School" otherwise

counter=1
while [ $counter -le 10 ]; do
    if [ $counter -eq 4 ]; then
        echo "bad luck"
    elif [ $counter -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((counter++))
done
